# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinanceApp' do
  
   
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinanceApp
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Charts'
  pod 'FirebaseUI'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  
  target 'FinanceAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinanceAppUITests' do
    # Pods for testing
  end

end
